
# how to store inventories - ignored ATM
Database: FlatFile

# msg when player does not have items to recover
YouAreNotDead: The Spirit Healer does not know you.

# warning when approaching an altar with anything but bare hands
NoWeapons: Show some respect when approaching the altar.

# second warning, first punishment; half food bar
Warn1: The Spirit Healer warned you.

# thrid warning, second punishment; half health bar
Warn2: You still don't want to listen?

# last warning, third punishment; kick player
Warn3: You annoyed the Spirit Healer.
